
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-04
owner: ucsb-cs156-s26
repo_name: team01-s26-04
pull_requests: [{"author":{"id":"U_kgDOCeRyWA","is_bot":false,"login":"Ertan10","name":"Ertan"},"headRefName":"Ertan-ReqRequestTable6","number":81,"title":"Ertan req request table6","url":"https://github.com/ucsb-cs156-s26/team01-s26-04/pull/81"},{"author":{"id":"U_kgDOCM7v4A","is_bot":false,"login":"t-ladha","name":""},"headRefName":"tl-DELETEMenuItemReview","number":78,"title":"DELETE endpoint for MenuItemReview","url":"https://github.com/ucsb-cs156-s26/team01-s26-04/pull/78"},{"author":{"id":"U_kgDOCeScdA","is_bot":false,"login":"GuaziBai","name":""},"headRefName":"annie-ucsborganization-get","number":77,"title":"Add GET endpoint for UCSBOrganization","url":"https://github.com/ucsb-cs156-s26/team01-s26-04/pull/77"},{"author":{"id":"U_kgDOCM7v4A","is_bot":false,"login":"t-ladha","name":""},"headRefName":"tl-PUTMenuItemReview","number":76,"title":"PUT method for MenuItemReview implemented","url":"https://github.com/ucsb-cs156-s26/team01-s26-04/pull/76"},{"author":{"id":"U_kgDOCeScdA","is_bot":false,"login":"GuaziBai","name":""},"headRefName":"annie-ucsborganization-put","number":74,"title":"Add PUT endpoint for UCSBOrganization","url":"https://github.com/ucsb-cs156-s26/team01-s26-04/pull/74"}]
